name: Instalert CD to Heroku - Dev

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
      - name: install npm dependencies
        run: (cd ./front-end/instalert && npm ci)
      - name: generate static assets
        run: (cd ./front-end/instalert && CI='' npm run build)
      - name: move static assets
        run: mv ./front-end/instalert/build ./app/src/main/resources
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: build with Gradle
        run: (./gradlew build jar && mv ./app/build/libs/app-1.0-SNAPSHOT.jar .)
      - name: Commit on the runner
        run:
          git config user.email "runner@github.com";
          git config user.name "Runner";
          git add -f ./app/src/main/resources/*;
          git add -f ./app-1.0-SNAPSHOT.jar;
          git commit -m "None"
      - name: Deploy to Heroku
        run: git push -f origin HEAD:dev-deploy